// ============================================================
//  data.js  –  All static game definitions
//  Add new resources or buildings here; nothing else needs to change.
// ============================================================

/** @type {Record<string, Resource>} */
export const RESOURCES = {
  iron_ore:  { id: "iron_ore",  name: "Iron Ore",   icon: "⛏️",  color: "#a07050" },
  coal:      { id: "coal",      name: "Coal",        icon: "🪨",  color: "#555566" },
  iron_bar:  { id: "iron_bar",  name: "Iron Bar",    icon: "🔩",  color: "#8899aa" },
  copper_ore:{ id: "copper_ore",name: "Copper Ore",  icon: "🟤",  color: "#b87333" },
  copper_bar:{ id: "copper_bar",name: "Copper Bar",  icon: "🔶",  color: "#da8a3a" },
  power:     { id: "power",     name: "Power",       icon: "⚡",  color: "#f59e0b" },
  gear:      { id: "gear",      name: "Gear",        icon: "⚙️",  color: "#aabbcc" },
  wire:      { id: "wire",      name: "Wire",        icon: "🪡",  color: "#da8a3a" },
  circuit:   { id: "circuit",   name: "Circuit",     icon: "💾",  color: "#4ade80" },
  points:    { id: "points",    name: "Tech Points",  icon: "🏆",  color: "#f59e0b" },
};

/** @type {Building[]} */
export const BUILDINGS = [
  // ── Mines ──────────────────────────────────────────────────
  {
    id: "iron_mine",
    name: "Iron Mine",
    icon: "⛏️",
    category: "extraction",
    description: "Extracts iron ore from the ground.",
    cost: { points: 0 },
    costScaling: 1.5,
    produces: { iron_ore: 1 },
    consumes: {},
    powerDraw: 0,
    baseTickMs: 2000,
    unlocked: true,
  },
  {
    id: "coal_mine",
    name: "Coal Mine",
    icon: "🪨",
    category: "extraction",
    description: "Digs up coal for fuel and power.",
    cost: { points: 5 },
    costScaling: 1.5,
    produces: { coal: 1 },
    consumes: {},
    powerDraw: 0,
    baseTickMs: 2000,
    unlocked: false,
    unlockRequires: { iron_ore: 10 },
  },
  {
    id: "copper_mine",
    name: "Copper Mine",
    icon: "🟤",
    category: "extraction",
    description: "Extracts copper ore.",
    cost: { points: 15 },
    costScaling: 1.6,
    produces: { copper_ore: 1 },
    consumes: {},
    powerDraw: 1,
    baseTickMs: 2500,
    unlocked: false,
    unlockRequires: { iron_bar: 5 },
  },

  // ── Smelters ───────────────────────────────────────────────
  {
    id: "iron_smelter",
    name: "Iron Smelter",
    icon: "🔥",
    category: "processing",
    description: "Turns iron ore + coal into iron bars.",
    cost: { points: 10 },
    costScaling: 1.7,
    produces: { iron_bar: 1 },
    consumes: { iron_ore: 2, coal: 1 },
    powerDraw: 2,
    baseTickMs: 3000,
    unlocked: false,
    unlockRequires: { iron_ore: 20, coal: 5 },
  },
  {
    id: "copper_smelter",
    name: "Copper Smelter",
    icon: "🔶",
    category: "processing",
    description: "Smelts copper ore into copper bars.",
    cost: { points: 20 },
    costScaling: 1.7,
    produces: { copper_bar: 1 },
    consumes: { copper_ore: 2, coal: 1 },
    powerDraw: 2,
    baseTickMs: 3000,
    unlocked: false,
    unlockRequires: { copper_ore: 10, iron_bar: 5 },
  },

  // ── Power ──────────────────────────────────────────────────
  {
    id: "coal_generator",
    name: "Coal Generator",
    icon: "⚡",
    category: "power",
    description: "Burns coal to generate power.",
    cost: { points: 25 },
    costScaling: 1.8,
    produces: { power: 5 },
    consumes: { coal: 1 },
    powerDraw: 0,
    baseTickMs: 2000,
    unlocked: false,
    unlockRequires: { coal: 20, iron_bar: 10 },
  },

  // ── Fabrication ────────────────────────────────────────────
  {
    id: "gear_press",
    name: "Gear Press",
    icon: "⚙️",
    category: "fabrication",
    description: "Stamps iron bars into gears.",
    cost: { points: 40 },
    costScaling: 1.9,
    produces: { gear: 1 },
    consumes: { iron_bar: 2 },
    powerDraw: 3,
    baseTickMs: 4000,
    unlocked: false,
    unlockRequires: { iron_bar: 30, power: 20 },
  },
  {
    id: "wire_drawer",
    name: "Wire Drawer",
    icon: "🪡",
    category: "fabrication",
    description: "Draws copper bars into wire.",
    cost: { points: 45 },
    costScaling: 1.9,
    produces: { wire: 1 },
    consumes: { copper_bar: 1 },
    powerDraw: 3,
    baseTickMs: 3500,
    unlocked: false,
    unlockRequires: { copper_bar: 15, power: 20 },
  },
  {
    id: "circuit_board",
    name: "Circuit Fab",
    icon: "💾",
    category: "fabrication",
    description: "Assembles gears + wire into circuits. Generates tech points.",
    cost: { points: 80 },
    costScaling: 2.0,
    produces: { circuit: 1, points: 2 },
    consumes: { gear: 1, wire: 2 },
    powerDraw: 5,
    baseTickMs: 5000,
    unlocked: false,
    unlockRequires: { gear: 10, wire: 10 },
  },
];

// Category display order and labels
export const CATEGORIES = [
  { id: "extraction",  label: "Extraction",  icon: "⛏️" },
  { id: "processing",  label: "Processing",  icon: "🔥" },
  { id: "power",       label: "Power",       icon: "⚡" },
  { id: "fabrication", label: "Fabrication", icon: "⚙️" },
];
